# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fs_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(2427, 1307)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(4000, 4000))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 2141, 1101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setAutoFillBackground(True)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(80, 100, 741, 461))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 113, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(400, 60, 46, 16))
        self.label_3.setObjectName("label_3")
        self.MongoDataBase = QtWidgets.QTextEdit(self.widget)
        self.MongoDataBase.setGeometry(QtCore.QRect(130, 90, 171, 31))
        self.MongoDataBase.setStyleSheet("color: rgb(0, 0, 0);")
        self.MongoDataBase.setObjectName("MongoDataBase")
        self.UserName = QtWidgets.QTextEdit(self.widget)
        self.UserName.setGeometry(QtCore.QRect(460, 0, 171, 31))
        self.UserName.setStyleSheet("color: rgb(0, 0, 0);")
        self.UserName.setObjectName("UserName")
        self.Password = QtWidgets.QTextEdit(self.widget)
        self.Password.setGeometry(QtCore.QRect(460, 50, 171, 31))
        self.Password.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.Password.setObjectName("Password")
        self.Port = QtWidgets.QTextEdit(self.widget)
        self.Port.setGeometry(QtCore.QRect(130, 40, 171, 31))
        self.Port.setStyleSheet("color: rgb(11, 11, 11);")
        self.Port.setObjectName("Port")
        self.Host = QtWidgets.QTextEdit(self.widget)
        self.Host.setGeometry(QtCore.QRect(130, 0, 171, 31))
        self.Host.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.Host.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.Host.setObjectName("Host")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 113, 16))
        self.label_17.setObjectName("label_17")
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setGeometry(QtCore.QRect(10, 90, 113, 16))
        self.label_26.setObjectName("label_26")
        self.ConnectToMongoDB = QtWidgets.QPushButton(self.widget)
        self.ConnectToMongoDB.setGeometry(QtCore.QRect(280, 200, 125, 30))
        self.ConnectToMongoDB.setStyleSheet("color:rgb(22, 22, 22)\n"
"font  75 10pt \"MS Shell Dlg 2\";")
        self.ConnectToMongoDB.setObjectName("ConnectToMongoDB")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.radioButton = QtWidgets.QRadioButton(self.page_2)
        self.radioButton.setGeometry(QtCore.QRect(170, 240, 82, 16))
        self.radioButton.setObjectName("radioButton")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(1210, 210, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.listWidget_3 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_3.setGeometry(QtCore.QRect(210, 170, 261, 192))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setMouseTracking(True)
        self.listWidget_3.setAutoFillBackground(False)
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.Box)
        self.listWidget_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_3.setTabKeyNavigation(True)
        self.listWidget_3.setAlternatingRowColors(False)
        self.listWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget_3.setMovement(QtWidgets.QListView.Free)
        self.listWidget_3.setObjectName("listWidget_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(640, 620, 301, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 420, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 210, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.page_3)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(210, 370, 104, 33))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit_2.setAutoFillBackground(True)
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit_2.setFrameShape(QtWidgets.QFrame.Box)
        self.plainTextEdit_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_2.setLineWidth(1)
        self.plainTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setDocumentTitle("")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setBackgroundVisible(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 180, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(720, 150, 121, 111))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(1030, 250, 751, 591))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.page_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(210, 620, 113, 33))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setAutoFillBackground(True)
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit_3.setFrameShape(QtWidgets.QFrame.Box)
        self.plainTextEdit_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_3.setLineWidth(1)
        self.plainTextEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setBackgroundVisible(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.page_3)
        self.comboBox_3.setEnabled(True)
        self.comboBox_3.setGeometry(QtCore.QRect(210, 80, 251, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setAutoFillBackground(True)
        self.comboBox_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setMaxVisibleItems(30)
        self.comboBox_3.setMaxCount(400)
        self.comboBox_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_3.setMinimumContentsLength(30)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.page_3)
        self.comboBox_7.setEnabled(True)
        self.comboBox_7.setGeometry(QtCore.QRect(210, 40, 251, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.comboBox_7.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(210, 130, 121, 33))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit.setAutoFillBackground(True)
        self.plainTextEdit.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit.setLineWidth(1)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("Shape Attribute")
        self.plainTextEdit.setBackgroundVisible(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(1030, 110, 441, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.tableWidget_3.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setStretchLastSection(True)
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(630, 380, 311, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setMouseTracking(True)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget.setAccessibleName("")
        self.tableWidget.setAccessibleDescription("")
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget.setIconSize(QtCore.QSize(6, 6))
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Selected_items")
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(206)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(31)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(96)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(1030, 210, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_10.setGeometry(QtCore.QRect(1440, 210, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.listWidget = QtWidgets.QListWidget(self.page_3)
        self.listWidget.setGeometry(QtCore.QRect(210, 660, 261, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 249))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setMouseTracking(True)
        self.listWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setAutoScroll(True)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.listWidget.setTabKeyNavigation(True)
        self.listWidget.setAlternatingRowColors(False)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setMovement(QtWidgets.QListView.Free)
        self.listWidget.setSelectionRectVisible(True)
        self.listWidget.setObjectName("listWidget")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_9.setGeometry(QtCore.QRect(114, 700, 81, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_8.setGeometry(QtCore.QRect(114, 670, 81, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_11.setGeometry(QtCore.QRect(1490, 120, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 450, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.listWidget_2 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_2.setGeometry(QtCore.QRect(210, 410, 261, 192))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setMouseTracking(True)
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.Box)
        self.listWidget_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_2.setTabKeyNavigation(True)
        self.listWidget_2.setAlternatingRowColors(False)
        self.listWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget_2.setMovement(QtWidgets.QListView.Free)
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 690, 111, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.page_3)
        self.checkBox.setGeometry(QtCore.QRect(490, 170, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_2.setGeometry(QtCore.QRect(490, 200, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"")
        self.checkBox_2.setObjectName("checkBox_2")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_4.setGeometry(QtCore.QRect(1440, 50, 351, 141))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.sign_2 = QtWidgets.QLabel(self.groupBox_4)
        self.sign_2.setGeometry(QtCore.QRect(20, 30, 61, 20))
        self.sign_2.setObjectName("sign_2")
        self.rec_name = QtWidgets.QLineEdit(self.groupBox_4)
        self.rec_name.setGeometry(QtCore.QRect(120, 30, 221, 22))
        self.rec_name.setObjectName("rec_name")
        self.sign_name_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.sign_name_2.setGeometry(QtCore.QRect(120, 80, 221, 22))
        self.sign_name_2.setObjectName("sign_name_2")
        self.sign_3 = QtWidgets.QLabel(self.groupBox_4)
        self.sign_3.setGeometry(QtCore.QRect(20, 80, 71, 20))
        self.sign_3.setObjectName("sign_3")
        self.fetch = QtWidgets.QPushButton(self.groupBox_4)
        self.fetch.setGeometry(QtCore.QRect(260, 110, 71, 28))
        self.fetch.setObjectName("fetch")
        self.sign_4 = QtWidgets.QLabel(self.groupBox_4)
        self.sign_4.setGeometry(QtCore.QRect(80, 30, 16, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sign_4.setFont(font)
        self.sign_4.setStyleSheet("color: rgb(255, 34, 5);")
        self.sign_4.setObjectName("sign_4")
        self.incBrightness = QtWidgets.QPushButton(self.groupBox_4)
        self.incBrightness.setGeometry(QtCore.QRect(164, 110, 40, 28))
        self.incBrightness.setObjectName("incBrightness")
        self.decBrightness = QtWidgets.QPushButton(self.groupBox_4)
        self.decBrightness.setGeometry(QtCore.QRect(120, 110, 41, 28))
        self.decBrightness.setObjectName("decBrightness")
        self.sign_6 = QtWidgets.QLabel(self.groupBox_4)
        self.sign_6.setGeometry(QtCore.QRect(68, 112, 51, 20))
        self.sign_6.setObjectName("sign_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_2.setGeometry(QtCore.QRect(1440, 190, 351, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 80, 281, 261))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.x0 = QtWidgets.QLabel(self.groupBox_3)
        self.x0.setGeometry(QtCore.QRect(30, 80, 55, 16))
        self.x0.setObjectName("x0")
        self.y0_2 = QtWidgets.QLabel(self.groupBox_3)
        self.y0_2.setGeometry(QtCore.QRect(30, 110, 55, 16))
        self.y0_2.setObjectName("y0_2")
        self.y0 = QtWidgets.QLabel(self.groupBox_3)
        self.y0.setGeometry(QtCore.QRect(30, 140, 55, 16))
        self.y0.setObjectName("y0")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(30, 170, 55, 16))
        self.label_9.setObjectName("label_9")
        self.x0_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.x0_3.setGeometry(QtCore.QRect(70, 80, 41, 22))
        self.x0_3.setReadOnly(True)
        self.x0_3.setObjectName("x0_3")
        self.y0_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.y0_3.setGeometry(QtCore.QRect(70, 110, 41, 22))
        self.y0_3.setReadOnly(True)
        self.y0_3.setObjectName("y0_3")
        self.y1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.y1.setGeometry(QtCore.QRect(70, 170, 41, 22))
        self.y1.setReadOnly(True)
        self.y1.setObjectName("y1")
        self.x1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.x1.setGeometry(QtCore.QRect(70, 140, 41, 22))
        self.x1.setReadOnly(True)
        self.x1.setObjectName("x1")
        self.x0_2 = QtWidgets.QLabel(self.groupBox_3)
        self.x0_2.setGeometry(QtCore.QRect(30, 50, 41, 20))
        self.x0_2.setObjectName("x0_2")
        self.sign_shape = QtWidgets.QLineEdit(self.groupBox_3)
        self.sign_shape.setGeometry(QtCore.QRect(70, 50, 201, 22))
        self.sign_shape.setReadOnly(True)
        self.sign_shape.setObjectName("sign_shape")
        self.sign_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.sign_name.setGeometry(QtCore.QRect(70, 20, 201, 22))
        self.sign_name.setReadOnly(True)
        self.sign_name.setObjectName("sign_name")
        self.sign = QtWidgets.QLabel(self.groupBox_3)
        self.sign.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.sign.setObjectName("sign")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(30, 200, 41, 16))
        self.label_11.setObjectName("label_11")
        self.signId = QtWidgets.QLineEdit(self.groupBox_3)
        self.signId.setGeometry(QtCore.QRect(70, 200, 41, 22))
        self.signId.setReadOnly(True)
        self.signId.setObjectName("signId")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(160, 80, 41, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(160, 110, 41, 16))
        self.label_13.setObjectName("label_13")
        self.width = QtWidgets.QLineEdit(self.groupBox_3)
        self.width.setGeometry(QtCore.QRect(230, 110, 41, 22))
        self.width.setReadOnly(True)
        self.width.setObjectName("width")
        self.Height = QtWidgets.QLineEdit(self.groupBox_3)
        self.Height.setGeometry(QtCore.QRect(230, 80, 41, 22))
        self.Height.setReadOnly(True)
        self.Height.setObjectName("Height")
        self.boxLabelIndex = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.boxLabelIndex.setGeometry(QtCore.QRect(90, 20, 51, 31))
        self.boxLabelIndex.setObjectName("boxLabelIndex")
        self.previousBox = QtWidgets.QPushButton(self.groupBox_2)
        self.previousBox.setGeometry(QtCore.QRect(30, 20, 41, 28))
        self.previousBox.setObjectName("previousBox")
        self.nextBox = QtWidgets.QPushButton(self.groupBox_2)
        self.nextBox.setGeometry(QtCore.QRect(160, 20, 41, 28))
        self.nextBox.setObjectName("nextBox")
        self.refresh = QtWidgets.QPushButton(self.groupBox_2)
        self.refresh.setGeometry(QtCore.QRect(270, 40, 71, 28))
        self.refresh.setObjectName("refresh")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_6.setGeometry(QtCore.QRect(1440, 510, 351, 291))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 161, 221))
        self.groupBox.setObjectName("groupBox")
        self.Triangle_Signs = QtWidgets.QCheckBox(self.groupBox)
        self.Triangle_Signs.setGeometry(QtCore.QRect(20, 30, 131, 20))
        self.Triangle_Signs.setChecked(False)
        self.Triangle_Signs.setObjectName("Triangle_Signs")
        self.Inv_Triangle_Signs = QtWidgets.QCheckBox(self.groupBox)
        self.Inv_Triangle_Signs.setGeometry(QtCore.QRect(20, 90, 141, 20))
        self.Inv_Triangle_Signs.setObjectName("Inv_Triangle_Signs")
        self.Circle_Signs_2 = QtWidgets.QCheckBox(self.groupBox)
        self.Circle_Signs_2.setGeometry(QtCore.QRect(20, 70, 141, 20))
        self.Circle_Signs_2.setObjectName("Circle_Signs_2")
        self.Pentagon_Signs = QtWidgets.QCheckBox(self.groupBox)
        self.Pentagon_Signs.setGeometry(QtCore.QRect(20, 110, 121, 20))
        self.Pentagon_Signs.setObjectName("Pentagon_Signs")
        self.Rectangle_Signs = QtWidgets.QCheckBox(self.groupBox)
        self.Rectangle_Signs.setGeometry(QtCore.QRect(20, 50, 121, 20))
        self.Rectangle_Signs.setObjectName("Rectangle_Signs")
        self.Octagon_Signs = QtWidgets.QCheckBox(self.groupBox)
        self.Octagon_Signs.setGeometry(QtCore.QRect(20, 130, 111, 20))
        self.Octagon_Signs.setObjectName("Octagon_Signs")
        self.Other_Signs = QtWidgets.QCheckBox(self.groupBox)
        self.Other_Signs.setGeometry(QtCore.QRect(20, 170, 111, 20))
        self.Other_Signs.setObjectName("Other_Signs")
        self.Diamond_Signs = QtWidgets.QCheckBox(self.groupBox)
        self.Diamond_Signs.setGeometry(QtCore.QRect(20, 150, 111, 20))
        self.Diamond_Signs.setObjectName("Diamond_Signs")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_5.setGeometry(QtCore.QRect(180, 20, 161, 221))
        self.groupBox_5.setObjectName("groupBox_5")
        self.Wrong_Shape = QtWidgets.QCheckBox(self.groupBox_5)
        self.Wrong_Shape.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.Wrong_Shape.setChecked(False)
        self.Wrong_Shape.setObjectName("Wrong_Shape")
        self.WrongBB = QtWidgets.QCheckBox(self.groupBox_5)
        self.WrongBB.setGeometry(QtCore.QRect(10, 70, 151, 20))
        self.WrongBB.setChecked(False)
        self.WrongBB.setObjectName("WrongBB")
        self.Wrong_Sign_Class = QtWidgets.QCheckBox(self.groupBox_5)
        self.Wrong_Sign_Class.setGeometry(QtCore.QRect(10, 50, 131, 20))
        self.Wrong_Sign_Class.setChecked(False)
        self.Wrong_Sign_Class.setObjectName("Wrong_Sign_Class")
        self.Wrong_attrib = QtWidgets.QCheckBox(self.groupBox_5)
        self.Wrong_attrib.setGeometry(QtCore.QRect(10, 90, 131, 20))
        self.Wrong_attrib.setChecked(False)
        self.Wrong_attrib.setObjectName("Wrong_attrib")
        self.update = QtWidgets.QPushButton(self.groupBox_6)
        self.update.setGeometry(QtCore.QRect(240, 250, 91, 28))
        self.update.setObjectName("update")
        self.imageLabel = QtWidgets.QLabel(self.page_4)
        self.imageLabel.setGeometry(QtCore.QRect(70, 50, 1341, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.nextImage = QtWidgets.QPushButton(self.page_4)
        self.nextImage.setGeometry(QtCore.QRect(1570, 760, 91, 28))
        self.nextImage.setObjectName("nextImage")
        self.previousImage = QtWidgets.QPushButton(self.page_4)
        self.previousImage.setGeometry(QtCore.QRect(1460, 760, 91, 28))
        self.previousImage.setObjectName("previousImage")
        self.isModified = QtWidgets.QLineEdit(self.page_4)
        self.isModified.setGeometry(QtCore.QRect(1440, 820, 351, 22))
        self.isModified.setReadOnly(True)
        self.isModified.setObjectName("isModified")
        self.count = QtWidgets.QLineEdit(self.page_4)
        self.count.setGeometry(QtCore.QRect(1572, 13, 141, 31))
        self.count.setReadOnly(True)
        self.count.setObjectName("count")
        self.sign_5 = QtWidgets.QLabel(self.page_4)
        self.sign_5.setGeometry(QtCore.QRect(1460, 20, 151, 20))
        self.sign_5.setObjectName("sign_5")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 110, 971, 731))
        self.groupBox_7.setMinimumSize(QtCore.QSize(851, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("color: rgb(200, 133, 0);\n"
"")
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setCheckable(False)
        self.groupBox_7.setChecked(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.collectionName = QtWidgets.QTextEdit(self.groupBox_7)
        self.collectionName.setGeometry(QtCore.QRect(140, 20, 171, 31))
        self.collectionName.setStyleSheet("color: rgb(0, 0, 0);")
        self.collectionName.setObjectName("collectionName")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_11.setGeometry(QtCore.QRect(330, 20, 251, 31))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.radioMain = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioMain.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.radioMain.setChecked(True)
        self.radioMain.setObjectName("radioMain")
        self.radioPVS = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioPVS.setGeometry(QtCore.QRect(120, 10, 82, 17))
        self.radioPVS.setObjectName("radioPVS")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 240, 531, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setStyleSheet("color: rgb(200, 133, 0);")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.SelectSignClass = QtWidgets.QLineEdit(self.groupBox_10)
        self.SelectSignClass.setGeometry(QtCore.QRect(10, 220, 256, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.SelectSignClass.setFont(font)
        self.SelectSignClass.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.SelectSignClass.setFrame(True)
        self.SelectSignClass.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.SelectSignClass.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.SelectSignClass.setObjectName("SelectSignClass")
        self.SignListV = QtWidgets.QListWidget(self.groupBox_10)
        self.SignListV.setGeometry(QtCore.QRect(10, 20, 256, 192))
        self.SignListV.setObjectName("SignListV")
        self.SignlistButton = QtWidgets.QPushButton(self.groupBox_10)
        self.SignlistButton.setGeometry(QtCore.QRect(280, 220, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SignlistButton.setFont(font)
        self.SignlistButton.setStyleSheet("color: rgb(0 0, 0);")
        self.SignlistButton.setObjectName("SignlistButton")
        self.label_18 = QtWidgets.QLabel(self.groupBox_10)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.SignList = QtWidgets.QListWidget(self.groupBox_10)
        self.SignList.setGeometry(QtCore.QRect(270, 20, 251, 131))
        self.SignList.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SignList.setLineWidth(8)
        self.SignList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SignList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SignList.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.SignList.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.SignList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.SignList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SignList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.SignList.setMovement(QtWidgets.QListView.Static)
        self.SignList.setFlow(QtWidgets.QListView.TopToBottom)
        self.SignList.setObjectName("SignList")
        self.SelectAllSigns = QtWidgets.QPushButton(self.groupBox_10)
        self.SelectAllSigns.setGeometry(QtCore.QRect(360, 220, 75, 25))
        self.SelectAllSigns.setStyleSheet("color: rgb(0 0, 0);")
        self.SelectAllSigns.setObjectName("SelectAllSigns")
        self.browseSignListForLabels = QtWidgets.QPushButton(self.groupBox_10)
        self.browseSignListForLabels.setGeometry(QtCore.QRect(280, 260, 75, 25))
        self.browseSignListForLabels.setStyleSheet("color: rgb(0, 0, 0);")
        self.browseSignListForLabels.setObjectName("browseSignListForLabels")
        self.selectSignFile_2 = QtWidgets.QPushButton(self.groupBox_10)
        self.selectSignFile_2.setGeometry(QtCore.QRect(560, 270, 75, 25))
        self.selectSignFile_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.selectSignFile_2.setObjectName("selectSignFile_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_10)
        self.label_10.setGeometry(QtCore.QRect(-220, 280, 101, 16))
        self.label_10.setObjectName("label_10")
        self.SelectSignFileForLabels = QtWidgets.QLineEdit(self.groupBox_10)
        self.SelectSignFileForLabels.setGeometry(QtCore.QRect(10, 260, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.SelectSignFileForLabels.setFont(font)
        self.SelectSignFileForLabels.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.SelectSignFileForLabels.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelectSignFileForLabels.setFrame(True)
        self.SelectSignFileForLabels.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.SelectSignFileForLabels.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.SelectSignFileForLabels.setObjectName("SelectSignFileForLabels")
        self.selectSignListForLabels = QtWidgets.QPushButton(self.groupBox_10)
        self.selectSignListForLabels.setGeometry(QtCore.QRect(360, 260, 75, 25))
        self.selectSignListForLabels.setStyleSheet("color: rgb(0, 0, 0);")
        self.selectSignListForLabels.setObjectName("selectSignListForLabels")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_12.setGeometry(QtCore.QRect(540, 240, 431, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setStyleSheet("color: rgb(200, 133, 0);")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.CountryListV = QtWidgets.QListWidget(self.groupBox_12)
        self.CountryListV.setGeometry(QtCore.QRect(10, 20, 171, 192))
        self.CountryListV.setMouseTracking(True)
        self.CountryListV.setAcceptDrops(True)
        self.CountryListV.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.CountryListV.setProperty("showDropIndicator", False)
        self.CountryListV.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.CountryListV.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.CountryListV.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.CountryListV.setObjectName("CountryListV")
        self.SelectCountry = QtWidgets.QLineEdit(self.groupBox_12)
        self.SelectCountry.setGeometry(QtCore.QRect(10, 220, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SelectCountry.setFont(font)
        self.SelectCountry.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.SelectCountry.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.SelectCountry.setObjectName("SelectCountry")
        self.CntryButton = QtWidgets.QPushButton(self.groupBox_12)
        self.CntryButton.setGeometry(QtCore.QRect(190, 220, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CntryButton.setFont(font)
        self.CntryButton.setStyleSheet("color: rgb(0 0, 0);")
        self.CntryButton.setObjectName("CntryButton")
        self.label_19 = QtWidgets.QLabel(self.groupBox_12)
        self.label_19.setGeometry(QtCore.QRect(10, 0, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.CountryList = QtWidgets.QListWidget(self.groupBox_12)
        self.CountryList.setGeometry(QtCore.QRect(190, 20, 171, 131))
        self.CountryList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.CountryList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.CountryList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.CountryList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CountryList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.CountryList.setMovement(QtWidgets.QListView.Static)
        self.CountryList.setFlow(QtWidgets.QListView.TopToBottom)
        self.CountryList.setObjectName("CountryList")
        self.SelectAllCountry = QtWidgets.QPushButton(self.groupBox_12)
        self.SelectAllCountry.setGeometry(QtCore.QRect(280, 220, 75, 25))
        self.SelectAllCountry.setStyleSheet("color: rgb(0 0, 0);")
        self.SelectAllCountry.setObjectName("SelectAllCountry")
        self.Extract_all = QtWidgets.QPushButton(self.groupBox_7)
        self.Extract_all.setGeometry(QtCore.QRect(500, 590, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Extract_all.setFont(font)
        self.Extract_all.setStyleSheet("color: rgb(0, 0, 0);")
        self.Extract_all.setObjectName("Extract_all")
        self.Extract = QtWidgets.QPushButton(self.groupBox_7)
        self.Extract.setGeometry(QtCore.QRect(390, 590, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Extract.setFont(font)
        self.Extract.setStyleSheet("color: rgb(0, 0, 0);")
        self.Extract.setObjectName("Extract")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(600, 10, 201, 191))
        self.groupBox_8.setObjectName("groupBox_8")
        self.sequenceListCheckBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.sequenceListCheckBox.setGeometry(QtCore.QRect(10, 20, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sequenceListCheckBox.setFont(font)
        self.sequenceListCheckBox.setObjectName("sequenceListCheckBox")
        self.countryListCheckBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.countryListCheckBox.setGeometry(QtCore.QRect(10, 40, 101, 25))
        self.countryListCheckBox.setObjectName("countryListCheckBox")
        self.sensorListCheckBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.sensorListCheckBox.setGeometry(QtCore.QRect(10, 60, 141, 25))
        self.sensorListCheckBox.setObjectName("sensorListCheckBox")
        self.signClassCheckBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.signClassCheckBox.setGeometry(QtCore.QRect(10, 80, 100, 25))
        self.signClassCheckBox.setObjectName("signClassCheckBox")
        self.Update = QtWidgets.QPushButton(self.groupBox_8)
        self.Update.setGeometry(QtCore.QRect(10, 140, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Update.setFont(font)
        self.Update.setStyleSheet("color:rgb(0, 0, 0)")
        self.Update.setObjectName("Update")
        self.mappedSequenceCheckBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.mappedSequenceCheckBox.setGeometry(QtCore.QRect(10, 100, 161, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.mappedSequenceCheckBox.setFont(font)
        self.mappedSequenceCheckBox.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.mappedSequenceCheckBox.setObjectName("mappedSequenceCheckBox")
        self.connectToColl = QtWidgets.QPushButton(self.groupBox_7)
        self.connectToColl.setGeometry(QtCore.QRect(390, 140, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connectToColl.setFont(font)
        self.connectToColl.setStyleSheet("color:rgb(0, 0, 0)")
        self.connectToColl.setObjectName("connectToColl")
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 20, 850, 80))
        self.groupBox_9.setMaximumSize(QtCore.QSize(850, 80))
        self.groupBox_9.setAutoFillBackground(False)
        self.groupBox_9.setStyleSheet("color: rgb(200, 133, 0);\n"
"")
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_16 = QtWidgets.QLabel(self.groupBox_9)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.SqlitePath = QtWidgets.QTextBrowser(self.groupBox_9)
        self.SqlitePath.setGeometry(QtCore.QRect(10, 40, 601, 31))
        self.SqlitePath.setObjectName("SqlitePath")
        self.browse = QtWidgets.QPushButton(self.groupBox_9)
        self.browse.setGeometry(QtCore.QRect(640, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.browse.setFont(font)
        self.browse.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.browse.setObjectName("browse")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_13.setGeometry(QtCore.QRect(30, 20, 1201, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setStyleSheet("color: rgb(220, 147, 0);")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.SelectSignClass_image = QtWidgets.QLineEdit(self.groupBox_13)
        self.SelectSignClass_image.setGeometry(QtCore.QRect(10, 390, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.SelectSignClass_image.setFont(font)
        self.SelectSignClass_image.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.SelectSignClass_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelectSignClass_image.setFrame(True)
        self.SelectSignClass_image.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.SelectSignClass_image.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.SelectSignClass_image.setObjectName("SelectSignClass_image")
        self.SignListV_image = QtWidgets.QListWidget(self.groupBox_13)
        self.SignListV_image.setGeometry(QtCore.QRect(10, 20, 621, 301))
        self.SignListV_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.SignListV_image.setObjectName("SignListV_image")
        self.label_21 = QtWidgets.QLabel(self.groupBox_13)
        self.label_21.setGeometry(QtCore.QRect(10, 0, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.SignList_image = QtWidgets.QListWidget(self.groupBox_13)
        self.SignList_image.setGeometry(QtCore.QRect(640, 20, 551, 251))
        self.SignList_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.SignList_image.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SignList_image.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SignList_image.setDragEnabled(True)
        self.SignList_image.setDragDropOverwriteMode(True)
        self.SignList_image.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.SignList_image.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.SignList_image.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.SignList_image.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SignList_image.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.SignList_image.setMovement(QtWidgets.QListView.Free)
        self.SignList_image.setFlow(QtWidgets.QListView.TopToBottom)
        self.SignList_image.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.SignList_image.setViewMode(QtWidgets.QListView.IconMode)
        self.SignList_image.setObjectName("SignList_image")
        self.SelectAllSigns_image = QtWidgets.QPushButton(self.groupBox_13)
        self.SelectAllSigns_image.setGeometry(QtCore.QRect(800, 400, 75, 25))
        self.SelectAllSigns_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelectAllSigns_image.setObjectName("SelectAllSigns_image")
        self.SelectSign_image = QtWidgets.QPushButton(self.groupBox_13)
        self.SelectSign_image.setGeometry(QtCore.QRect(700, 400, 75, 25))
        self.SelectSign_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelectSign_image.setObjectName("SelectSign_image")
        self.SelectSignFile = QtWidgets.QLineEdit(self.groupBox_13)
        self.SelectSignFile.setGeometry(QtCore.QRect(120, 450, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.SelectSignFile.setFont(font)
        self.SelectSignFile.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.SelectSignFile.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelectSignFile.setFrame(True)
        self.SelectSignFile.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.SelectSignFile.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.SelectSignFile.setObjectName("SelectSignFile")
        self.label_8 = QtWidgets.QLabel(self.groupBox_13)
        self.label_8.setGeometry(QtCore.QRect(20, 460, 101, 16))
        self.label_8.setObjectName("label_8")
        self.browseSignList = QtWidgets.QPushButton(self.groupBox_13)
        self.browseSignList.setGeometry(QtCore.QRect(700, 450, 75, 25))
        self.browseSignList.setStyleSheet("color: rgb(0, 0, 0);")
        self.browseSignList.setObjectName("browseSignList")
        self.selectSignFile = QtWidgets.QPushButton(self.groupBox_13)
        self.selectSignFile.setGeometry(QtCore.QRect(800, 450, 75, 25))
        self.selectSignFile.setStyleSheet("color: rgb(0, 0, 0);")
        self.selectSignFile.setObjectName("selectSignFile")
        self.groupBox_14 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_14.setGeometry(QtCore.QRect(1240, 20, 351, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setStyleSheet("color: rgb(220, 147, 0);")
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.CountryListV_image = QtWidgets.QListWidget(self.groupBox_14)
        self.CountryListV_image.setGeometry(QtCore.QRect(30, 30, 121, 311))
        self.CountryListV_image.setMouseTracking(True)
        self.CountryListV_image.setAcceptDrops(True)
        self.CountryListV_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.CountryListV_image.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.CountryListV_image.setProperty("showDropIndicator", False)
        self.CountryListV_image.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.CountryListV_image.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.CountryListV_image.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.CountryListV_image.setObjectName("CountryListV_image")
        self.SelectCountry_image = QtWidgets.QLineEdit(self.groupBox_14)
        self.SelectCountry_image.setGeometry(QtCore.QRect(30, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SelectCountry_image.setFont(font)
        self.SelectCountry_image.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.SelectCountry_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelectCountry_image.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.SelectCountry_image.setObjectName("SelectCountry_image")
        self.label_22 = QtWidgets.QLabel(self.groupBox_14)
        self.label_22.setGeometry(QtCore.QRect(10, 0, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("")
        self.label_22.setObjectName("label_22")
        self.CountryList_image = QtWidgets.QListWidget(self.groupBox_14)
        self.CountryList_image.setGeometry(QtCore.QRect(180, 30, 101, 241))
        self.CountryList_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.CountryList_image.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.CountryList_image.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.CountryList_image.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.CountryList_image.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CountryList_image.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.CountryList_image.setMovement(QtWidgets.QListView.Static)
        self.CountryList_image.setFlow(QtWidgets.QListView.TopToBottom)
        self.CountryList_image.setObjectName("CountryList_image")
        self.SelectAllCountry_image = QtWidgets.QPushButton(self.groupBox_14)
        self.SelectAllCountry_image.setGeometry(QtCore.QRect(250, 350, 75, 25))
        self.SelectAllCountry_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelectAllCountry_image.setObjectName("SelectAllCountry_image")
        self.CntryButton_image = QtWidgets.QPushButton(self.groupBox_14)
        self.CntryButton_image.setGeometry(QtCore.QRect(160, 350, 75, 25))
        self.CntryButton_image.setStyleSheet("color: rgb(0, 0, 0);")
        self.CntryButton_image.setObjectName("CntryButton_image")
        self.dumpImages = QtWidgets.QPushButton(self.page_6)
        self.dumpImages.setGeometry(QtCore.QRect(900, 660, 93, 28))
        self.dumpImages.setObjectName("dumpImages")
        self.label_24 = QtWidgets.QLabel(self.page_6)
        self.label_24.setGeometry(QtCore.QRect(50, 670, 871, 120))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("C:/Users/uid41624/.designer/backup/Continental_Logo_png.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.chipsBox = QtWidgets.QCheckBox(self.page_6)
        self.chipsBox.setGeometry(QtCore.QRect(990, 610, 70, 17))
        self.chipsBox.setObjectName("chipsBox")
        self.rawBox = QtWidgets.QCheckBox(self.page_6)
        self.rawBox.setGeometry(QtCore.QRect(830, 610, 70, 17))
        self.rawBox.setChecked(False)
        self.rawBox.setObjectName("rawBox")
        self.groupBox_15 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_15.setGeometry(QtCore.QRect(1600, 20, 201, 131))
        self.groupBox_15.setStyleSheet("color: rgb(220, 147, 0);")
        self.groupBox_15.setObjectName("groupBox_15")
        self.lightConditionDay = QtWidgets.QRadioButton(self.groupBox_15)
        self.lightConditionDay.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.lightConditionDay.setStyleSheet("color:rgb(0, 0, 0)")
        self.lightConditionDay.setCheckable(True)
        self.lightConditionDay.setChecked(False)
        self.lightConditionDay.setAutoExclusive(False)
        self.lightConditionDay.setObjectName("lightConditionDay")
        self.lightConditionNight = QtWidgets.QRadioButton(self.groupBox_15)
        self.lightConditionNight.setGeometry(QtCore.QRect(100, 30, 82, 17))
        self.lightConditionNight.setStyleSheet("color:rgb(0, 0, 0)")
        self.lightConditionNight.setChecked(False)
        self.lightConditionNight.setAutoExclusive(False)
        self.lightConditionNight.setObjectName("lightConditionNight")
        self.signCount = QtWidgets.QLineEdit(self.page_6)
        self.signCount.setGeometry(QtCore.QRect(1680, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signCount.setFont(font)
        self.signCount.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.signCount.setStyleSheet("color: rgb(0, 0, 0);")
        self.signCount.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.signCount.setText("")
        self.signCount.setObjectName("signCount")
        self.label_4 = QtWidgets.QLabel(self.page_6)
        self.label_4.setGeometry(QtCore.QRect(1610, 170, 47, 13))
        self.label_4.setStyleSheet("color: rgb(220, 147, 0);")
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2427, 21))
        self.menubar.setObjectName("menubar")
        self.menuData_Preparation = QtWidgets.QMenu(self.menubar)
        self.menuData_Preparation.setObjectName("menuData_Preparation")
        self.menuSynchronization = QtWidgets.QMenu(self.menuData_Preparation)
        self.menuSynchronization.setObjectName("menuSynchronization")
        self.menuData_Analysis = QtWidgets.QMenu(self.menubar)
        self.menuData_Analysis.setObjectName("menuData_Analysis")
        self.menuClassifier_Design = QtWidgets.QMenu(self.menubar)
        self.menuClassifier_Design.setObjectName("menuClassifier_Design")
        self.menuPerformance_Evaluation = QtWidgets.QMenu(self.menubar)
        self.menuPerformance_Evaluation.setObjectName("menuPerformance_Evaluation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDMS_to_MongoDB = QtWidgets.QAction(MainWindow)
        self.actionDMS_to_MongoDB.setObjectName("actionDMS_to_MongoDB")
        self.data_analysis = QtWidgets.QAction(MainWindow)
        self.data_analysis.setObjectName("data_analysis")
        self.actionAnnotations = QtWidgets.QAction(MainWindow)
        self.actionAnnotations.setObjectName("actionAnnotations")
        self.actionSQL_to_MongoDB = QtWidgets.QAction(MainWindow)
        self.actionSQL_to_MongoDB.setObjectName("actionSQL_to_MongoDB")
        self.actionImage_Dump = QtWidgets.QAction(MainWindow)
        self.actionImage_Dump.setObjectName("actionImage_Dump")
        self.menuSynchronization.addAction(self.actionDMS_to_MongoDB)
        self.menuSynchronization.addAction(self.actionAnnotations)
        self.menuData_Preparation.addAction(self.menuSynchronization.menuAction())
        self.menuData_Preparation.addAction(self.actionSQL_to_MongoDB)
        self.menuData_Preparation.addAction(self.actionImage_Dump)
        self.menuData_Analysis.addAction(self.data_analysis)
        self.menubar.addAction(self.menuData_Preparation.menuAction())
        self.menubar.addAction(self.menuData_Analysis.menuAction())
        self.menubar.addAction(self.menuClassifier_Design.menuAction())
        self.menubar.addAction(self.menuPerformance_Evaluation.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.listWidget.setCurrentRow(-1)
        self.listWidget_2.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Four Seasons"))
        self.label.setText(_translate("MainWindow", "MongoDb Server Name "))
        self.label_2.setText(_translate("MainWindow", "User Name "))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.MongoDataBase.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri,sans-serif\'; font-size:11pt;\">sr_labels</span></p></body></html>"))
        self.UserName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri,sans-serif\'; font-size:11pt;\">sr_write_labels</span></p></body></html>"))
        self.Password.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri,sans-serif\'; font-size:11pt;\">g4*yGQbk{Dcxz3T</span></p></body></html>"))
        self.Port.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">27017</span></p></body></html>"))
        self.Host.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri,sans-serif\'; font-size:11pt;\">OZD2472U.conti.de</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "Port"))
        self.label_26.setText(_translate("MainWindow", "DataBase"))
        self.ConnectToMongoDB.setText(_translate("MainWindow", "Connect "))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.pushButton_3.setText(_translate("MainWindow", "Pop-up graph window"))
        self.listWidget_3.setSortingEnabled(True)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sign vs Country"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Count"))
        self.pushButton_6.setText(_translate("MainWindow", "Select All"))
        self.pushButton_5.setText(_translate("MainWindow", "Deselect All"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Sign ID"))
        self.pushButton_4.setText(_translate("MainWindow", "Select All"))
        self.label_5.setText(_translate("MainWindow", "Sign_Image"))
        self.label_6.setText(_translate("MainWindow", "Graph"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "Country ID"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Collection List"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Select Profile"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Histogram Height"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Histogram Width"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Scale Height"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Scale Width"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "Aspect Ratio"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Size"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Min Range"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Max Range"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bin Size"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Selected_profile"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Collection_list"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Shape_Attribute"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sign_ID"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Country_ID"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Click for graph"))
        self.pushButton_10.setText(_translate("MainWindow", "Export CSV"))
        self.listWidget.setSortingEnabled(True)
        self.pushButton_9.setText(_translate("MainWindow", "Deselect All"))
        self.pushButton_8.setText(_translate("MainWindow", "Select All"))
        self.pushButton_11.setText(_translate("MainWindow", "Reset"))
        self.pushButton_7.setText(_translate("MainWindow", "Deselect All"))
        self.listWidget_2.setSortingEnabled(True)
        self.pushButton_2.setText(_translate("MainWindow", "Click_for_count"))
        self.checkBox.setText(_translate("MainWindow", "With Image"))
        self.checkBox_2.setText(_translate("MainWindow", "Without Image"))
        self.sign_2.setText(_translate("MainWindow", "Sourcefile"))
        self.sign_3.setText(_translate("MainWindow", "Timestamp"))
        self.fetch.setText(_translate("MainWindow", "Fetch"))
        self.sign_4.setText(_translate("MainWindow", "*"))
        self.incBrightness.setText(_translate("MainWindow", "+"))
        self.decBrightness.setText(_translate("MainWindow", "-"))
        self.sign_6.setText(_translate("MainWindow", "Brightness"))
        self.groupBox_2.setTitle(_translate("MainWindow", "BoxLabels"))
        self.x0.setText(_translate("MainWindow", "x0"))
        self.y0_2.setText(_translate("MainWindow", "y0"))
        self.y0.setText(_translate("MainWindow", "x1"))
        self.label_9.setText(_translate("MainWindow", "y1"))
        self.x0_2.setText(_translate("MainWindow", "Shape"))
        self.sign.setText(_translate("MainWindow", "Sign"))
        self.label_11.setText(_translate("MainWindow", "SignId"))
        self.label_12.setText(_translate("MainWindow", "Height"))
        self.label_13.setText(_translate("MainWindow", "Width"))
        self.previousBox.setText(_translate("MainWindow", "<"))
        self.nextBox.setText(_translate("MainWindow", ">"))
        self.refresh.setText(_translate("MainWindow", "Refresh"))
        self.groupBox.setTitle(_translate("MainWindow", "Anno_Completed"))
        self.Triangle_Signs.setText(_translate("MainWindow", "Triangle_Signs"))
        self.Inv_Triangle_Signs.setText(_translate("MainWindow", "Inv_Triangle_Signs"))
        self.Circle_Signs_2.setText(_translate("MainWindow", "Circle_Signs"))
        self.Pentagon_Signs.setText(_translate("MainWindow", "Pentagon_Signs"))
        self.Rectangle_Signs.setText(_translate("MainWindow", "Rectangle_Signs"))
        self.Octagon_Signs.setText(_translate("MainWindow", "Octagon_Signs"))
        self.Other_Signs.setText(_translate("MainWindow", "Other_Signs"))
        self.Diamond_Signs.setText(_translate("MainWindow", "Diamond_Signs"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Complaint Box"))
        self.Wrong_Shape.setText(_translate("MainWindow", "Wrong Shape"))
        self.WrongBB.setText(_translate("MainWindow", "Wrong Bounding Box"))
        self.Wrong_Sign_Class.setText(_translate("MainWindow", "Wrong Sign Class"))
        self.Wrong_attrib.setText(_translate("MainWindow", "Wrong Atrributes"))
        self.update.setText(_translate("MainWindow", "Update"))
        self.nextImage.setText(_translate("MainWindow", " NEXT"))
        self.previousImage.setText(_translate("MainWindow", "Previous"))
        self.sign_5.setText(_translate("MainWindow", "Completed / Total"))
        self.groupBox_7.setTitle(_translate("MainWindow", "MongoDB"))
        self.label_7.setText(_translate("MainWindow", "Collection Name"))
        self.collectionName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioMain.setText(_translate("MainWindow", "Main Signs"))
        self.radioPVS.setText(_translate("MainWindow", "PVS"))
        self.SignlistButton.setText(_translate("MainWindow", "Select "))
        self.label_18.setText(_translate("MainWindow", "Select SignClass"))
        self.SelectAllSigns.setText(_translate("MainWindow", "Select All"))
        self.browseSignListForLabels.setText(_translate("MainWindow", "..."))
        self.selectSignFile_2.setText(_translate("MainWindow", "Select"))
        self.label_10.setText(_translate("MainWindow", "Read From File"))
        self.selectSignListForLabels.setText(_translate("MainWindow", "Select"))
        self.CntryButton.setText(_translate("MainWindow", "Select "))
        self.label_19.setText(_translate("MainWindow", "Select Countries"))
        self.SelectAllCountry.setText(_translate("MainWindow", "Select All"))
        self.Extract_all.setText(_translate("MainWindow", "Extract All"))
        self.Extract.setText(_translate("MainWindow", "Extract"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Update Methods"))
        self.sequenceListCheckBox.setText(_translate("MainWindow", "Sequence List"))
        self.countryListCheckBox.setText(_translate("MainWindow", "Country List"))
        self.sensorListCheckBox.setText(_translate("MainWindow", "Sensor List"))
        self.signClassCheckBox.setText(_translate("MainWindow", "Sign Class"))
        self.Update.setText(_translate("MainWindow", "UPDATE"))
        self.mappedSequenceCheckBox.setText(_translate("MainWindow", "Mapped Sequence"))
        self.connectToColl.setText(_translate("MainWindow", "Connect"))
        self.label_16.setText(_translate("MainWindow", "SqLite Path"))
        self.SqlitePath.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p></body></html>"))
        self.browse.setText(_translate("MainWindow", "..."))
        self.label_21.setText(_translate("MainWindow", "Select SignClass"))
        self.SelectAllSigns_image.setText(_translate("MainWindow", "Select All"))
        self.SelectSign_image.setText(_translate("MainWindow", "Select"))
        self.label_8.setText(_translate("MainWindow", "Read From File"))
        self.browseSignList.setText(_translate("MainWindow", "..."))
        self.selectSignFile.setText(_translate("MainWindow", "Select"))
        self.label_22.setText(_translate("MainWindow", "Select Countries"))
        self.SelectAllCountry_image.setText(_translate("MainWindow", "Select All"))
        self.CntryButton_image.setText(_translate("MainWindow", "Select"))
        self.dumpImages.setText(_translate("MainWindow", "DUMP"))
        self.chipsBox.setText(_translate("MainWindow", "CHIPS"))
        self.rawBox.setText(_translate("MainWindow", "RAW"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Light Condition"))
        self.lightConditionDay.setText(_translate("MainWindow", "Day"))
        self.lightConditionNight.setText(_translate("MainWindow", "Night"))
        self.label_4.setText(_translate("MainWindow", "Count"))
        self.menuData_Preparation.setTitle(_translate("MainWindow", "Data Preparation"))
        self.menuSynchronization.setTitle(_translate("MainWindow", "Synchronization"))
        self.menuData_Analysis.setTitle(_translate("MainWindow", "Data Analysis"))
        self.menuClassifier_Design.setTitle(_translate("MainWindow", "Classifier Design"))
        self.menuPerformance_Evaluation.setTitle(_translate("MainWindow", "Performance Evaluation"))
        self.actionDMS_to_MongoDB.setText(_translate("MainWindow", "DMS to MongoDB"))
        self.data_analysis.setText(_translate("MainWindow", "Sign Profile"))
        self.actionAnnotations.setText(_translate("MainWindow", "Annotations"))
        self.actionSQL_to_MongoDB.setText(_translate("MainWindow", "SQL to MongoDB"))
        self.actionImage_Dump.setText(_translate("MainWindow", "Image Dump"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

